# Generated by Django 5.1.1 on 2024-09-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('max_incorrect_guesses', models.IntegerField()),
                ('current_state', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('InProgress', 'InProgress'), ('Won', 'Won'), ('Lost', 'Lost')], default='InProgress', max_length=20)),
            ],
        ),
    ]
